language: python
python:
- '3.4'
- '3.5'
script: python -m unittest
notifications:
  slack:
    secure: EO5YAy6SWgqJFZSCx0eDfjgOe/uXLqv5v5W+mf44C/aiO6BJLSMWMBb9UdUBgH5OFGv4lnxdPW6QWe7SKeVES5FWqAtqWaVHtWFYAUddjzbPEaCII/qqCTbeRvtsaIoAZpIYgRJpR6FttmWqpGplCIT+ipyiMGvbJeMCTNcSILQcwJ+WP2BX6ekxYPcNXO0nr3OTLf4z5bb1xfjLhK3xIOlsipy89VGZCW5nwj6BzXLCd20R68Hp/5XYZg/7ZCRTu1q/7HWKSEzH/UYu76bixbiJFe8uQKIW6CVhCrt+XEhcRw9ggXUuF4Me/vRiNLfGMr6t8EQ0AQtRctZe4Fyplfe/TF4ZZdrWo8YLbi332vDXr7LXvV14U40IgJC660MFd16U3P3INltsOLIjTp6a2MxMGfHNaVlEYWEQ1tGYatgQFnfH1g/SCDVzv5RLKEX0EBE8YQGO5paOJiLMXe3u/c5SIg1S3Z9ZMvY54MlgYF9LMyNuNBEtmvzD+QBEHJgwG6VbkCIf1we/90pfpt8q1fRJC9WamKaf6mkPxTlFsWTI3rPBp9rwlg0RNVJvVISIf8cFZkejlYPcem6VCuNwLjD/hu3zGcobQ6Jf7m62J+8GKbpbdUEU2Xux0aD9OFokZE6ZyxMvdb671NACAbQneB7dEda/ixhe2NhoXyIqwmU=
